pipeline {
    agent any
    tools {
        maven 'mvn'
    }
    stages {
        stage('Compile') {
            steps {
                sh 'mvn clean compile'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
         stage('Build Package') {
            steps {
                sh 'mvn package'
            }
        }
    }
}
